name: "deployment"
on: 
  push:
    branches:
      - "main"
jobs:
  build-package:
    name: "build project"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: use node.js
        uses: actions/setup-node@v1
        run: 
          npm install
          npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build-package
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'ap-southeast-3'   # optional: defaults to us-east-1
        SOURCE_DIR: 'build'      # optional: defaults to entire repository



  